### ISSUE TITLE
Learn how git works and how to push code to Github

### ISSUE THREAD

**Issue by Origho-precious** [alabobriggs/ministry-of-developers#11]

**Comment by DINIPRE** [comment]
I have learnt on how git works and i also pushed my first code to my git repositories : you can check it out for me. Thanks

**Comment by Origho-precious** [comment]
@DINIPRE kindly send a link to the github repository as a comment here.

**Comment by DINIPRE** [comment]
This is the link https://github.com/DINIPRE/dinipre.io

**Comment by DINIPRE** [comment]
@Origho-precious https://github.com/DINIPRE/dinipre.io

**Comment by Origho-precious** [comment]
Great job @DINIPRE!

**Comment by Origho-precious** [comment]
Great job @DINIPRE!
