### ISSUE TITLE
Learn how to deploy apps on netlify and deploy your projects

### ISSUE THREAD

**Issue by Origho-precious** [alabobriggs/ministry-of-developers#13]
#### Description
> Learn how to deploy apps on netlify and deploy your projects

#### References
> Use this [article](https://www.freecodecamp.org/news/publish-your-website-netlify-github/) 

#### Additional Info
> If you prefer learning with videos, search for "how to deploy html websites on netlify"

**Comment by DINIPRE** [comment]
I've learnt that already but I'm having issues with hosting my site on gitpages and netlify

**Comment by DINIPRE** [comment]
This is the link to my live site url
https://wonderful-lamington-a973c3.netlify.app/
