### ISSUE TITLE
Setup meeting with Emeka

### ISSUE THREAD

**Issue by alabobriggs** [alabobriggs/ministry-of-developers#4]
@iamfortune  Have a meeting with @Emeka-techDev. Understand his current skill level and what he is currently learning

### Feedback
- @iamfortune leave a comment with a list of skillsets Emeka has
- Also a comment on general findings about him

**Comment by iamfortune** [comment]
- Subject @Emeka-techDev  
- Skill Level - He's learnt HTML, CSS, JS, Solidity 
- He's currently learning - React.js 
- Plan for him to be a Software Engineer with a focus on **Blockchain development** 
- Based in Port-Harcourt
- Hobbies include Table tennis
- He's a graduate from UniPort 💯

**Comment by alabobriggs** [comment]
Solid. @Emeka-techDev We will do some catch up again
