### ISSUE TITLE
Setup meeting with Zaya

### ISSUE THREAD

**Issue by alabobriggs** [alabobriggs/ministry-of-developers#7]
Setup meeting to learn about Zaya's skillset

**Comment by Origho-precious** [comment]
## Feedback

I just concluded my meeting with @DINIPRE 

### Findings
- Her hobbies: writing and reading.
- She wants to learn web development.
- She started her tech journey recent and she has been able to learn HTML and CSS. She has built a couple of projects as well.
- She is currently learning Javascript but paused for a bit to learn git and she's having issues understanding it at the moment. (I want to setup some time with her to explain how it works) 
- As far as resources go, she has a 12 hours javascript course that she's using right now.
