### ISSUE TITLE
Setup meeting with Christine

### ISSUE THREAD

**Issue by alabobriggs** [alabobriggs/ministry-of-developers#9]
@Origho-precious   Have a meeting with @Dinnayachristine. Understand her current skill level, available resources, challenges, ETC

### Feedback
- Also comment on general findings about her

**Comment by Origho-precious** [comment]
## Feedback

I just concluded my meeting with @Dinnayachristine .

### Findings
- Her hobbies: baking, trying out new recipes, creating contents on tiktok, and editing photos.
- She's just starting her tech journey and she wants to learn web development.
- She has experience using editing tools hence why she wants to learn web development.
- She did a research on web development and found a careerfoundry article that explained what web development is about ( I reviewed the article and it's good). 
- The blog post has a newsletter that she subscribed to, so she will be getting one web dev tutorial everyday for 5 days.
